# Generated by scripts/generate_flavor_config.py. Do not edit.
set(SOLAR_OS_FLAVOR_NAME "core")
set(SOLAR_OS_FLAVOR_DESCRIPTION "Usable SolarOS terminal baseline for constrained boards.")
set(SOLAR_OS_FLAVOR_FILE "flavors\\core.toml")
set(SOLAR_OS_PACKAGE_CATALOG_FILE "packages\\solar_os_packages.toml")
set(SOLAR_OS_PACKAGE_GROUP_LIST "bootstrap hardware_shell filesystem sd_storage audio_support control_bindings signal_processing vector_math gpio onewire i2c uart pwm logging battery_monitor embedded_docs serial_terminal editor pager files io clock calculator plot sheet logic_analyzer sump bridge daq gpio_keys ps2_keyboard midi ssd1306 cardkb analog_joystick ps2_mouse sdmmc tca8418")
set(SOLAR_OS_PACKAGE_LIST "bootstrap.runtime bootstrap.shell system.shell core.fs-commands service.zip service.text_search service.sd service.audio service.midi service.controls service.streams service.resources service.engines service.vector service.dsp service.gpio service.onewire service.ps2 service.logic service.i2c service.expansion service.radio service.link expansion.ssd1306 expansion.cardkb expansion.tca8418 expansion.analog-joystick expansion.gpio-keys expansion.ps2-keyboard expansion.ps2-mouse expansion.sdmmc service.json service.json-scan service.crypto service.uart service.battery service.rtc service.schedule service.pwm app.clock app.com app.edit app.less app.docs app.files app.io service.expr app.calc app.plot app.logic app.sheet job.bridge job.log job.batmon job.daq job.controls job.gpio-keys job.ps2-keyboard job.midi job.sump")
set(SOLAR_OS_PACKAGE_ID_LIST "core_runtime core_shell system_shell core_fs_commands service_zip service_text_search service_sd service_audio service_midi service_controls service_streams service_resources service_engines service_vector service_dsp service_gpio service_onewire service_ps2 service_logic service_i2c service_expansion service_radio service_link expansion_ssd1306 expansion_cardkb tca8418 expansion_analog_joystick expansion_gpio_keys expansion_ps2_keyboard expansion_ps2_mouse expansion_sdmmc service_json service_json_scan service_crypto service_uart service_battery service_rtc service_schedule service_pwm app_clock app_com app_edit app_less app_docs app_files app_io service_expr app_calc app_plot app_logic app_sheet job_bridge job_log job_batmon job_daq job_controls job_gpio_keys job_ps2_keyboard job_midi job_sump")
set(SOLAR_OS_PACKAGE_REQUIRED_CAPABILITIES "sd gpio i2c expansion_i2c pwm expansion_gpio uart gfx battery expansion_uart cdc")
set(SOLAR_OS_JOBS_MAX 9)
set(SOLAR_OS_PACKAGE_BOOTSTRAP 1)
set(SOLAR_OS_PACKAGE_HARDWARE_SHELL 1)
set(SOLAR_OS_PACKAGE_FILESYSTEM 1)
set(SOLAR_OS_PACKAGE_WIFI 0)
set(SOLAR_OS_PACKAGE_BLUETOOTH 0)
set(SOLAR_OS_PACKAGE_SD_STORAGE 1)
set(SOLAR_OS_PACKAGE_AUDIO_SUPPORT 1)
set(SOLAR_OS_PACKAGE_CONTROL_BINDINGS 1)
set(SOLAR_OS_PACKAGE_SIGNAL_PROCESSING 1)
set(SOLAR_OS_PACKAGE_VECTOR_MATH 1)
set(SOLAR_OS_PACKAGE_GPIO 1)
set(SOLAR_OS_PACKAGE_ONEWIRE 1)
set(SOLAR_OS_PACKAGE_I2C 1)
set(SOLAR_OS_PACKAGE_SPI 0)
set(SOLAR_OS_PACKAGE_UART 1)
set(SOLAR_OS_PACKAGE_ADC 0)
set(SOLAR_OS_PACKAGE_PWM 1)
set(SOLAR_OS_PACKAGE_BOARD_BUTTONS 0)
set(SOLAR_OS_PACKAGE_ADC_DPAD 0)
set(SOLAR_OS_PACKAGE_OTA 0)
set(SOLAR_OS_PACKAGE_DOCUMENTATION_SYNC 0)
set(SOLAR_OS_PACKAGE_DEVICE_FLASHER 0)
set(SOLAR_OS_PACKAGE_LOGGING 1)
set(SOLAR_OS_PACKAGE_BATTERY_MONITOR 1)
set(SOLAR_OS_PACKAGE_EMBEDDED_DOCS 1)
set(SOLAR_OS_PACKAGE_SERIAL_TERMINAL 1)
set(SOLAR_OS_PACKAGE_EDITOR 1)
set(SOLAR_OS_PACKAGE_PAGER 1)
set(SOLAR_OS_PACKAGE_FILES 1)
set(SOLAR_OS_PACKAGE_IO 1)
set(SOLAR_OS_PACKAGE_CLOCK 1)
set(SOLAR_OS_PACKAGE_CALCULATOR 1)
set(SOLAR_OS_PACKAGE_PLOT 1)
set(SOLAR_OS_PACKAGE_SHEET 1)
set(SOLAR_OS_PACKAGE_LOGIC_ANALYZER 1)
set(SOLAR_OS_PACKAGE_SUMP 1)
set(SOLAR_OS_PACKAGE_BRIDGE 1)
set(SOLAR_OS_PACKAGE_DAQ 1)
set(SOLAR_OS_PACKAGE_GPIO_KEYS 1)
set(SOLAR_OS_PACKAGE_PS2_KEYBOARD 1)
set(SOLAR_OS_PACKAGE_MIDI 1)
set(SOLAR_OS_PACKAGE_SSH 0)
set(SOLAR_OS_PACKAGE_HTTP_CLIENT 0)
set(SOLAR_OS_PACKAGE_WEB_BROWSER 0)
set(SOLAR_OS_PACKAGE_FTP 0)
set(SOLAR_OS_PACKAGE_TELNET 0)
set(SOLAR_OS_PACKAGE_HTTP_SERVER 0)
set(SOLAR_OS_PACKAGE_DISPLAY_SERVER 0)
set(SOLAR_OS_PACKAGE_WIREGUARD 0)
set(SOLAR_OS_PACKAGE_MQTT 0)
set(SOLAR_OS_PACKAGE_NTP 0)
set(SOLAR_OS_PACKAGE_SLIP 0)
set(SOLAR_OS_PACKAGE_OSC 0)
set(SOLAR_OS_PACKAGE_INBOX 0)
set(SOLAR_OS_PACKAGE_CONTACTS 0)
set(SOLAR_OS_PACKAGE_CHAT 0)
set(SOLAR_OS_PACKAGE_CHAT_GATEWAY 0)
set(SOLAR_OS_PACKAGE_GATEWAY_SYNC 0)
set(SOLAR_OS_PACKAGE_CHAT_SERVER 0)
set(SOLAR_OS_PACKAGE_EMAIL 0)
set(SOLAR_OS_PACKAGE_AGENT 0)
set(SOLAR_OS_PACKAGE_ESPNOW 0)
set(SOLAR_OS_PACKAGE_POCSAG 0)
set(SOLAR_OS_PACKAGE_RADIO_LINK 0)
set(SOLAR_OS_PACKAGE_MESHCORE 0)
set(SOLAR_OS_PACKAGE_AUDIO_COMMANDS 0)
set(SOLAR_OS_PACKAGE_PLAYER 0)
set(SOLAR_OS_PACKAGE_RECORDER 0)
set(SOLAR_OS_PACKAGE_SYNTH 0)
set(SOLAR_OS_PACKAGE_FUNCTION_GENERATOR 0)
set(SOLAR_OS_PACKAGE_WEBRADIO 0)
set(SOLAR_OS_PACKAGE_READER 0)
set(SOLAR_OS_PACKAGE_WRITER 0)
set(SOLAR_OS_PACKAGE_NOTES 0)
set(SOLAR_OS_PACKAGE_IMAGE_VIEWER 0)
set(SOLAR_OS_PACKAGE_SKETCH 0)
set(SOLAR_OS_PACKAGE_INVADERS 0)
set(SOLAR_OS_PACKAGE_GAMEBOY 0)
set(SOLAR_OS_PACKAGE_PYTHON 0)
set(SOLAR_OS_PACKAGE_LUA 0)
set(SOLAR_OS_PACKAGE_PLAYGROUND 0)
set(SOLAR_OS_PACKAGE_RFM69 0)
set(SOLAR_OS_PACKAGE_RFM95 0)
set(SOLAR_OS_PACKAGE_PCD8544 0)
set(SOLAR_OS_PACKAGE_SSD1683 0)
set(SOLAR_OS_PACKAGE_SSD1306 1)
set(SOLAR_OS_PACKAGE_CARDKB 1)
set(SOLAR_OS_PACKAGE_ANALOG_JOYSTICK 1)
set(SOLAR_OS_PACKAGE_PS2_MOUSE 1)
set(SOLAR_OS_PACKAGE_SDSPI 0)
set(SOLAR_OS_PACKAGE_SDMMC 1)
set(SOLAR_OS_PACKAGE_NEOPIXEL 0)
set(SOLAR_OS_PACKAGE_AUDIO_PWM 0)
set(SOLAR_OS_PACKAGE_PCM5102 0)
set(SOLAR_OS_PACKAGE_PCM1808 0)
set(SOLAR_OS_PACKAGE_ES8311 0)
set(SOLAR_OS_PACKAGE_ESP32_DAC 0)
set(SOLAR_OS_PACKAGE_ST7305 0)
set(SOLAR_OS_PACKAGE_ILI9341 0)
set(SOLAR_OS_PACKAGE_ST7796 0)
set(SOLAR_OS_PACKAGE_CVBS 0)
set(SOLAR_OS_PACKAGE_VGA 0)
set(SOLAR_OS_PACKAGE_FT6336 0)
set(SOLAR_OS_PACKAGE_PCF85063 0)
set(SOLAR_OS_PACKAGE_SHTC3 0)
set(SOLAR_OS_PACKAGE_BATTERY_ADC 0)
set(SOLAR_OS_PACKAGE_M5TAB5_DISPLAY 0)
set(SOLAR_OS_PACKAGE_M5TAB5_TOUCH 0)
set(SOLAR_OS_PACKAGE_INA226 0)
set(SOLAR_OS_PACKAGE_RX8130 0)
set(SOLAR_OS_PACKAGE_USB_HID 0)
set(SOLAR_OS_PACKAGE_CL32_CORE 0)
set(SOLAR_OS_PACKAGE_TLORA_PAGER_CORE 0)
set(SOLAR_OS_PACKAGE_TCA8418 1)
set(SOLAR_OS_PACKAGE_SX1262 0)
set(SOLAR_OS_PACKAGE_ROTARY_ENCODER 0)
set(SOLAR_OS_PACKAGE_BQ27220 0)

set(SOLAR_OS_PACKAGE_CORE_RUNTIME 1)
set(SOLAR_OS_PACKAGE_SERVICE_OTA 0)
set(SOLAR_OS_PACKAGE_SERVICE_DOCS 0)
set(SOLAR_OS_PACKAGE_SERVICE_FLASH 0)
set(SOLAR_OS_PACKAGE_CORE_SHELL 1)
set(SOLAR_OS_PACKAGE_SYSTEM_SHELL 1)
set(SOLAR_OS_PACKAGE_SERVICE_INBOX 0)
set(SOLAR_OS_PACKAGE_SERVICE_CONTACTS 0)
set(SOLAR_OS_PACKAGE_SERVICE_CREDENTIALS 0)
set(SOLAR_OS_PACKAGE_CORE_FS_COMMANDS 1)
set(SOLAR_OS_PACKAGE_SERVICE_ZIP 1)
set(SOLAR_OS_PACKAGE_SERVICE_WIFI 0)
set(SOLAR_OS_PACKAGE_SERVICE_WIREGUARD 0)
set(SOLAR_OS_PACKAGE_SERVICE_ESPNOW 0)
set(SOLAR_OS_PACKAGE_SERVICE_NET 0)
set(SOLAR_OS_PACKAGE_SERVICE_OSC 0)
set(SOLAR_OS_PACKAGE_SERVICE_SCRIPT_NET 0)
set(SOLAR_OS_PACKAGE_SERVICE_FTP 0)
set(SOLAR_OS_PACKAGE_SERVICE_MQTT 0)
set(SOLAR_OS_PACKAGE_SERVICE_SSH 0)
set(SOLAR_OS_PACKAGE_SERVICE_MAIL 0)
set(SOLAR_OS_PACKAGE_SERVICE_GATEWAY 0)
set(SOLAR_OS_PACKAGE_SERVICE_MESSAGING 0)
set(SOLAR_OS_PACKAGE_CHAT_TRANSPORT_GATEWAY 0)
set(SOLAR_OS_PACKAGE_SERVICE_HTTP_CLIENT 0)
set(SOLAR_OS_PACKAGE_SERVICE_PLAYGROUND 0)
set(SOLAR_OS_PACKAGE_SERVICE_HTTP_SERVER 0)
set(SOLAR_OS_PACKAGE_SERVICE_AGENT 0)
set(SOLAR_OS_PACKAGE_SERVICE_SCRIPT_RUNNER 0)
set(SOLAR_OS_PACKAGE_SERVICE_IMAGE 0)
set(SOLAR_OS_PACKAGE_SERVICE_DOCUMENT 0)
set(SOLAR_OS_PACKAGE_SERVICE_TEXT_SEARCH 1)
set(SOLAR_OS_PACKAGE_SERVICE_BLE 0)
set(SOLAR_OS_PACKAGE_SERVICE_HID 0)
set(SOLAR_OS_PACKAGE_SERVICE_SD 1)
set(SOLAR_OS_PACKAGE_SERVICE_AUDIO 1)
set(SOLAR_OS_PACKAGE_SERVICE_AUDIO_CODECS 0)
set(SOLAR_OS_PACKAGE_SERVICE_WEBRADIO 0)
set(SOLAR_OS_PACKAGE_SERVICE_SYNTH 0)
set(SOLAR_OS_PACKAGE_SERVICE_MIDI 1)
set(SOLAR_OS_PACKAGE_SERVICE_CONTROLS 1)
set(SOLAR_OS_PACKAGE_SERVICE_STREAMS 1)
set(SOLAR_OS_PACKAGE_SERVICE_RESOURCES 1)
set(SOLAR_OS_PACKAGE_SERVICE_ENGINES 1)
set(SOLAR_OS_PACKAGE_SERVICE_VECTOR 1)
set(SOLAR_OS_PACKAGE_SERVICE_DSP 1)
set(SOLAR_OS_PACKAGE_SERVICE_SIGNAL_WIDGETS 0)
set(SOLAR_OS_PACKAGE_SERVICE_MEDIA_WIDGETS 0)
set(SOLAR_OS_PACKAGE_SERVICE_STORAGE_BROWSER 0)
set(SOLAR_OS_PACKAGE_SERVICE_PLAYER_PLAYLIST 0)
set(SOLAR_OS_PACKAGE_SERVICE_GPIO 1)
set(SOLAR_OS_PACKAGE_SERVICE_ONEWIRE 1)
set(SOLAR_OS_PACKAGE_SERVICE_PS2 1)
set(SOLAR_OS_PACKAGE_SERVICE_LOGIC 1)
set(SOLAR_OS_PACKAGE_SERVICE_I2C 1)
set(SOLAR_OS_PACKAGE_SERVICE_SPI 0)
set(SOLAR_OS_PACKAGE_SERVICE_EXPANSION 1)
set(SOLAR_OS_PACKAGE_SERVICE_RADIO 1)
set(SOLAR_OS_PACKAGE_SERVICE_LINK 1)
set(SOLAR_OS_PACKAGE_SERVICE_MESHCORE 0)
set(SOLAR_OS_PACKAGE_EXPANSION_RFM69 0)
set(SOLAR_OS_PACKAGE_EXPANSION_RFM95 0)
set(SOLAR_OS_PACKAGE_EXPANSION_PCD8544 0)
set(SOLAR_OS_PACKAGE_EXPANSION_SSD1683 0)
set(SOLAR_OS_PACKAGE_EXPANSION_SSD1306 1)
set(SOLAR_OS_PACKAGE_EXPANSION_CARDKB 1)
set(SOLAR_OS_PACKAGE_BOARD_CL32_CORE 0)
set(SOLAR_OS_PACKAGE_TLORA_PAGER_CORE 0)
set(SOLAR_OS_PACKAGE_TCA8418 1)
set(SOLAR_OS_PACKAGE_SX1262 0)
set(SOLAR_OS_PACKAGE_ROTARY_ENCODER 0)
set(SOLAR_OS_PACKAGE_BQ27220 0)
set(SOLAR_OS_PACKAGE_EXPANSION_ANALOG_JOYSTICK 1)
set(SOLAR_OS_PACKAGE_EXPANSION_GPIO_KEYS 1)
set(SOLAR_OS_PACKAGE_EXPANSION_PS2_KEYBOARD 1)
set(SOLAR_OS_PACKAGE_EXPANSION_PS2_MOUSE 1)
set(SOLAR_OS_PACKAGE_EXPANSION_SDSPI 0)
set(SOLAR_OS_PACKAGE_EXPANSION_SDMMC 1)
set(SOLAR_OS_PACKAGE_EXPANSION_NEOPIXEL 0)
set(SOLAR_OS_PACKAGE_EXPANSION_AUDIO_PWM 0)
set(SOLAR_OS_PACKAGE_EXPANSION_PCM5102 0)
set(SOLAR_OS_PACKAGE_EXPANSION_PCM1808 0)
set(SOLAR_OS_PACKAGE_DRIVER_AUDIO_ES8311_CODECS 0)
set(SOLAR_OS_PACKAGE_DRIVER_AUDIO_ESP32_DAC 0)
set(SOLAR_OS_PACKAGE_DRIVER_DISPLAY_ST7305 0)
set(SOLAR_OS_PACKAGE_DRIVER_DISPLAY_ILI9341 0)
set(SOLAR_OS_PACKAGE_DRIVER_DISPLAY_ST7796 0)
set(SOLAR_OS_PACKAGE_DRIVER_DISPLAY_CVBS_PAL 0)
set(SOLAR_OS_PACKAGE_DRIVER_DISPLAY_VGA32 0)
set(SOLAR_OS_PACKAGE_DRIVER_FT6336 0)
set(SOLAR_OS_PACKAGE_DRIVER_PCF85063 0)
set(SOLAR_OS_PACKAGE_DRIVER_SHTC3 0)
set(SOLAR_OS_PACKAGE_DRIVER_BATTERY_ADC 0)
set(SOLAR_OS_PACKAGE_SERVICE_JSON 1)
set(SOLAR_OS_PACKAGE_SERVICE_JSON_SCAN 1)
set(SOLAR_OS_PACKAGE_SERVICE_CRYPTO 1)
set(SOLAR_OS_PACKAGE_SERVICE_UART 1)
set(SOLAR_OS_PACKAGE_SERVICE_BATTERY 1)
set(SOLAR_OS_PACKAGE_SERVICE_RTC 1)
set(SOLAR_OS_PACKAGE_SERVICE_SCHEDULE 1)
set(SOLAR_OS_PACKAGE_SERVICE_SENSORS 0)
set(SOLAR_OS_PACKAGE_SERVICE_ADC 0)
set(SOLAR_OS_PACKAGE_SERVICE_PWM 1)
set(SOLAR_OS_PACKAGE_SERVICE_BUTTONS 0)
set(SOLAR_OS_PACKAGE_SERVICE_ADC_DPAD 0)
set(SOLAR_OS_PACKAGE_APP_APLAY 0)
set(SOLAR_OS_PACKAGE_APP_ARECORD 0)
set(SOLAR_OS_PACKAGE_APP_RECORDER 0)
set(SOLAR_OS_PACKAGE_APP_PLAYER 0)
set(SOLAR_OS_PACKAGE_APP_SYNTH 0)
set(SOLAR_OS_PACKAGE_APP_FUNCGEN 0)
set(SOLAR_OS_PACKAGE_APP_SSH 0)
set(SOLAR_OS_PACKAGE_APP_SCP 0)
set(SOLAR_OS_PACKAGE_APP_CURL 0)
set(SOLAR_OS_PACKAGE_APP_WEBRADIO 0)
set(SOLAR_OS_PACKAGE_APP_TELNET 0)
set(SOLAR_OS_PACKAGE_APP_WEB 0)
set(SOLAR_OS_PACKAGE_APP_CHAT 0)
set(SOLAR_OS_PACKAGE_APP_AGENT 0)
set(SOLAR_OS_PACKAGE_APP_EMAIL 0)
set(SOLAR_OS_PACKAGE_APP_INBOX 0)
set(SOLAR_OS_PACKAGE_APP_CONTACTS 0)
set(SOLAR_OS_PACKAGE_APP_VIEW 0)
set(SOLAR_OS_PACKAGE_APP_SKETCH 0)
set(SOLAR_OS_PACKAGE_APP_INVADERS 0)
set(SOLAR_OS_PACKAGE_APP_GAMEBOY 0)
set(SOLAR_OS_PACKAGE_APP_PYTHON 0)
set(SOLAR_OS_PACKAGE_APP_LUA 0)
set(SOLAR_OS_PACKAGE_APP_PLAYGROUND 0)
set(SOLAR_OS_PACKAGE_APP_CLOCK 1)
set(SOLAR_OS_PACKAGE_APP_COM 1)
set(SOLAR_OS_PACKAGE_APP_EDIT 1)
set(SOLAR_OS_PACKAGE_APP_LESS 1)
set(SOLAR_OS_PACKAGE_APP_DOCS 1)
set(SOLAR_OS_PACKAGE_APP_FLASH 0)
set(SOLAR_OS_PACKAGE_APP_READER 0)
set(SOLAR_OS_PACKAGE_APP_WRITER 0)
set(SOLAR_OS_PACKAGE_APP_FILES 1)
set(SOLAR_OS_PACKAGE_APP_FTP 0)
set(SOLAR_OS_PACKAGE_APP_IO 1)
set(SOLAR_OS_PACKAGE_APP_NOTES 0)
set(SOLAR_OS_PACKAGE_SERVICE_EXPR 1)
set(SOLAR_OS_PACKAGE_APP_CALC 1)
set(SOLAR_OS_PACKAGE_APP_PLOT 1)
set(SOLAR_OS_PACKAGE_APP_LOGIC 1)
set(SOLAR_OS_PACKAGE_APP_SHEET 1)
set(SOLAR_OS_PACKAGE_JOB_HTTPD 0)
set(SOLAR_OS_PACKAGE_JOB_DISPLAYD 0)
set(SOLAR_OS_PACKAGE_JOB_CHATD 0)
set(SOLAR_OS_PACKAGE_JOB_TELNETD 0)
set(SOLAR_OS_PACKAGE_JOB_FTPD 0)
set(SOLAR_OS_PACKAGE_JOB_GATEWAY_SYNC 0)
set(SOLAR_OS_PACKAGE_JOB_EMAIL_SYNC 0)
set(SOLAR_OS_PACKAGE_JOB_SLIP 0)
set(SOLAR_OS_PACKAGE_JOB_BRIDGE 1)
set(SOLAR_OS_PACKAGE_JOB_LOG 1)
set(SOLAR_OS_PACKAGE_JOB_BATMON 1)
set(SOLAR_OS_PACKAGE_JOB_DAQ 1)
set(SOLAR_OS_PACKAGE_JOB_CONTROLS 1)
set(SOLAR_OS_PACKAGE_JOB_GPIO_KEYS 1)
set(SOLAR_OS_PACKAGE_JOB_PS2_KEYBOARD 1)
set(SOLAR_OS_PACKAGE_JOB_MIDI 1)
set(SOLAR_OS_PACKAGE_JOB_SUMP 1)
set(SOLAR_OS_PACKAGE_JOB_NTP_SYNC 0)
set(SOLAR_OS_PACKAGE_JOB_OSC 0)
set(SOLAR_OS_PACKAGE_JOB_POCSAG 0)
set(SOLAR_OS_PACKAGE_JOB_RADIO_LINK 0)
set(SOLAR_OS_PACKAGE_JOB_ESPNOW_LINK 0)
set(SOLAR_OS_PACKAGE_JOB_MESHCORE 0)
set(SOLAR_OS_PACKAGE_DRIVER_DISPLAY_M5TAB5 0)
set(SOLAR_OS_PACKAGE_DRIVER_POINTER_M5TAB5 0)
set(SOLAR_OS_PACKAGE_DRIVER_BATTERY_INA226 0)
set(SOLAR_OS_PACKAGE_DRIVER_RTC_RX8130 0)

set(SOLAR_OS_PACKAGE_SRCS
    "main.c"
    "solar_os.c"
    "solar_os_jobs.c"
    "solar_os_queue.c"
    "solar_os_scheduler.c"
    "solar_os_task.c"
    "drivers/flash_storage.c"
    "apps/solar_os_app_file_types.c"
    "apps/solar_os_app_registry.c"
    "jobs/solar_os_job_registry.c"
    "services/solar_os_board_caps.c"
    "services/solar_os_board_boot.c"
    "services/solar_os_boot_services.c"
    "services/solar_os_cdc.c"
    "services/solar_os_clipboard.c"
    "services/solar_os_display.c"
    "services/solar_os_frame_presenter.c"
    "services/solar_os_gfx.c"
    "services/solar_os_identity.c"
    "services/solar_os_input.c"
    "services/solar_os_keys.c"
    "services/solar_os_log.c"
    "services/solar_os_manual.c"
    "services/solar_os_memory.c"
    "services/solar_os_messaging_types.c"
    "services/solar_os_nvs_backup.c"
    "services/solar_os_port.c"
    "services/solar_os_port_shell.c"
    "services/solar_os_parameters.c"
    "services/solar_os_power.c"
    "services/solar_os_ramfs.c"
    "services/solar_os_sessions.c"
    "services/solar_os_splash.c"
    "services/solar_os_storage.c"
    "services/solar_os_terminal.c"
    "services/solar_os_terminal_geometry.c"
    "services/solar_os_terminal_preferences.c"
    "services/solar_os_time.c"
    "services/solar_os_timezone.c"
    "services/solar_os_tui.c"
    "services/solar_os_tui_widgets.c"
    "apps/solar_os_shell.c"
    "shell/solar_os_shell_common.c"
    "shell/solar_os_shell_launch.c"
    "shell/solar_os_shell_parse.c"
    "shell/solar_os_shell_commands.c"
    "shell/solar_os_shell_input.c"
    "shell/solar_os_shell_completion.c"
    "shell/solar_os_shell_io.c"
    "shell/solar_os_shell_manual.c"
    "shell/solar_os_shell_line.c"
    "shell/solar_os_shell_setterm_tui.c"
    "shell/solar_os_shell_system.c"
    "shell/solar_os_shell_schedule.c"
    "shell/solar_os_vt100.c"
    "services/solar_os_transfer.c"
    "services/solar_os_zmodem.c"
    "shell/solar_os_shell_hardware.c"
    "shell/solar_os_shell_fs.c"
    "services/solar_os_zip.c"
    "services/solar_os_text_search.c"
    "services/solar_os_audio.c"
    "services/solar_os_audio_player.c"
    "services/solar_os_audio_pcm.c"
    "services/solar_os_midi.c"
    "services/solar_os_midi_codec.c"
    "services/solar_os_controls.c"
    "shell/solar_os_shell_controls.c"
    "services/solar_os_stream.c"
    "drivers/routed_spi_bus.c"
    "services/solar_os_buses.c"
    "services/solar_os_resources.c"
    "services/solar_os_pins.c"
    "services/solar_os_engines.c"
    "services/solar_os_vector.c"
    "services/solar_os_dsp.c"
    "services/solar_os_gpio.c"
    "services/solar_os_status_led.c"
    "services/solar_os_onewire.c"
    "drivers/ps2_bus.c"
    "services/solar_os_ps2_keyboard.c"
    "services/solar_os_ps2_mouse.c"
    "services/solar_os_logic.c"
    "services/solar_os_i2c.c"
    "services/solar_os_expansion.c"
    "shell/solar_os_shell_expansion.c"
    "services/solar_os_radio.c"
    "shell/solar_os_shell_radio.c"
    "shell/solar_os_shell_radio_tui.c"
    "services/solar_os_link.c"
    "services/solar_os_link_repeater.c"
    "services/solar_os_link_stream.c"
    "services/solar_os_link_messaging.c"
    "shell/solar_os_shell_link.c"
    "drivers/ssd1306.c"
    "services/solar_os_ssd1306.c"
    "services/solar_os_ssd1306_driver.c"
    "services/solar_os_cardkb.c"
    "services/solar_os_cardkb_codec.c"
    "services/solar_os_cardkb_driver.c"
    "services/solar_os_tca8418.c"
    "services/solar_os_tca8418_driver.c"
    "services/solar_os_analog_joystick.c"
    "services/solar_os_analog_joystick_driver.c"
    "services/solar_os_gpio_keys.c"
    "services/solar_os_gpio_keys_driver.c"
    "services/solar_os_ps2_keyboard_device.c"
    "services/solar_os_ps2_keyboard_driver.c"
    "services/solar_os_ps2_mouse_device.c"
    "services/solar_os_ps2_mouse_driver.c"
    "board/solar_os_board_storage_sd.c"
    "drivers/sd_card.c"
    "services/solar_os_sdmmc.c"
    "services/solar_os_sdmmc_driver.c"
    "services/solar_os_json.c"
    "services/solar_os_json_scan.c"
    "services/solar_os_crypto.c"
    "services/solar_os_uart.c"
    "services/solar_os_battery.c"
    "services/solar_os_rtc.c"
    "services/solar_os_schedule.c"
    "services/solar_os_pwm.c"
    "apps/solar_os_clock.c"
    "apps/solar_os_com.c"
    "apps/solar_os_edit.c"
    "services/solar_os_syntax.c"
    "apps/solar_os_less.c"
    "apps/solar_os_docs_app.c"
    "apps/solar_os_files.c"
    "apps/solar_os_io.c"
    "services/solar_os_expr.c"
    "apps/solar_os_calc.c"
    "apps/solar_os_plot.c"
    "apps/solar_os_logic_app.c"
    "apps/solar_os_sheet.c"
    "jobs/solar_os_bridge_job.c"
    "jobs/solar_os_log_job.c"
    "jobs/solar_os_batmon_job.c"
    "jobs/solar_os_daq_job.c"
    "shell/solar_os_shell_daq.c"
    "jobs/solar_os_controls_job.c"
    "jobs/solar_os_gpio_keys_job.c"
    "jobs/solar_os_ps2_keyboard_job.c"
    "jobs/solar_os_midi_job.c"
    "shell/solar_os_shell_midi.c"
    "jobs/solar_os_sump_job.c"
)
set(SOLAR_OS_PACKAGE_REQUIRES
    "esp_driver_gpio"
    "esp_driver_usb_serial_jtag"
    "esp_event"
    "esp_pm"
    "esp_rom"
    "esp_timer"
    "fatfs"
    "heap"
    "nvs_flash"
    "u8g2"
    "wear_levelling"
    "esp_driver_spi"
    "espressif__esp-dsp"
    "onewire_bus"
    "esp_hw_support"
    "esp_driver_i2c"
    "esp_driver_sdmmc"
    "sdmmc"
    "espressif__cjson"
    "mbedtls"
    "esp_driver_uart"
    "esp_driver_ledc"
)
