set(SOLAR_OS_BOARD_POINTER_DRIVER "m5tab5")
include("${CMAKE_CURRENT_LIST_DIR}/i2c_esp_idf.cmake")
list(APPEND SOLAR_OS_BOARD_REQUIRED_PACKAGES driver_pointer_m5tab5)
list(APPEND SOLAR_OS_BOARD_COMPILE_DEFINITIONS SOLAR_OS_BOARD_POINTER_M5TAB5=1)
